### ISSUE TITLE
URL for soccersim cant be used by DoE students

### ISSUE THREAD

**Issue by linda-graham3** [rcjnsw/soccersim#19]

**Comment by kcnotes** [comment]
Hi Linda, thank you for the message.

I'll speak with some of the teachers in RoboCupJunior and see what I can do to either get the site unblocked or moved.

**Comment by linda-graham3** [comment]
?thanks. Someone from the committee could message the department and explain the need for the URL to be accessed by students. It would probably have more weight coming from a committee member although I will message as well. The URL is https://webfilter.det.nsw.edu.au/? . It is being denied based on the fact that it is shareware/freeware.


thank you


Ms Linda Graham
Head Teacher TAS
Technology Teacher
NESA Accreditation: Highly Accomplished


Rooty Hill High School
Learning, Leadership & Achievement
North Parade, Rooty Hill NSW 2766
P.O. Box 70, Rooty Hill  NSW  2766
Phone:  02 9625 8104
Fax:      02 9625 4208

Find us on:
Web: www.rootyhill-h.schools.nsw.edu.au
Facebook: www.facebook.com/rootyhillhs
RHHS Alumni Network: www.linkedin.com (GROUP: Rooty Hill High School)
________________________________

**Comment by kcnotes** [comment]
Hey there, can you try and see if this is accessible? [https://tools.robocupjunior.org.au/blockcode-soccer-sim/](https://tools.robocupjunior.org.au/blockcode-soccer-sim/)

**Comment by linda-graham3** [comment]
?thanks. that works


Ms Linda Graham
Head Teacher TAS
Technology Teacher
NESA Accreditation: Highly Accomplished


Rooty Hill High School
Learning, Leadership & Achievement
North Parade, Rooty Hill NSW 2766
P.O. Box 70, Rooty Hill  NSW  2766
Phone:  02 9625 8104
Fax:      02 9625 4208

Find us on:
Web: www.rootyhill-h.schools.nsw.edu.au
Facebook: www.facebook.com/rootyhillhs
RHHS Alumni Network: www.linkedin.com (GROUP: Rooty Hill High School)
________________________________

**Comment by kcnotes** [comment]
Thank you, hope the students have fun with the programming!

**Comment by linda-graham3** [comment]
?thanks. Im sure they will. I can see a lot of work has gone into this.


regards


Ms Linda Graham
Head Teacher TAS
Technology Teacher
NESA Accreditation: Highly Accomplished


Rooty Hill High School
Learning, Leadership & Achievement
North Parade, Rooty Hill NSW 2766
P.O. Box 70, Rooty Hill  NSW  2766
Phone:  02 9625 8104
Fax:      02 9625 4208

Find us on:
Web: www.rootyhill-h.schools.nsw.edu.au
Facebook: www.facebook.com/rootyhillhs
RHHS Alumni Network: www.linkedin.com (GROUP: Rooty Hill High School)
________________________________

**Comment by kcnotes** [comment]
Hi Linda, could you quickly get us a screenshot of the blocked page, for https://rcjnsw.github.io/soccersim/ ? You can attach an image to the issue by 'pasting' it into the comment box.

**Comment by linda-graham3** [comment]
<img width="561" alt="screen shot" src="https://user-images.githubusercontent.com/73265909/96825052-01956400-147c-11eb-84f4-d50ef85da56f.PNG">

I hope this opens ok

**Comment by kcnotes** [comment]
Thanks Linda - we've talked to someone and the link [https://rcjnsw.github.io/soccer-sim/](https://rcjnsw.github.io/soccer-sim/) should now be unblocked. Could you check for us (since this link will be where our latest changes and bug fixes are released?)

If it still is not working, then we will need to know if your school is on a Proxy or an I@E website.
